# Generated by Django 3.1.5 on 2021-02-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200)),
                ('watch_state', models.CharField(choices=[('TW', 'To watch'), ('WD', 'Watched')], default='TW', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_title', models.CharField(max_length=200)),
                ('watch_state', models.CharField(choices=[('TW', 'To watch'), ('WG', 'Watching'), ('WD', 'Watched')], default='TW', max_length=2)),
            ],
        ),
    ]
