# Generated by Django 3.1.5 on 2021-02-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_auto_20210204_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='watch_state',
            field=models.CharField(choices=[('TW', 'To Watch'), ('WD', 'Watched')], default='TW', max_length=2),
        ),
    ]
