# Generated by Django 3.1.5 on 2021-02-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0003_auto_20210206_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='watch_state',
            field=models.CharField(choices=[('TW', 'To watch'), ('WD', 'Watched')], default='TW', max_length=2),
        ),
    ]
