# Generated by Django 3.1.5 on 2021-02-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0005_auto_20210208_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
