# Generated by Django 3.1.5 on 2021-02-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0008_auto_20210223_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_url',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='page',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
