# Generated by Django 3.1.5 on 2021-03-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0010_movie_featured_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='queued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='show',
            name='queued',
            field=models.BooleanField(default=False),
        ),
    ]
