# Generated by Django 3.1.5 on 2021-03-15 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0011_auto_20210313_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='featured_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='show',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='watchlist.watchlist'),
        ),
        migrations.AddField(
            model_name='show',
            name='synopsis',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
