# Generated by Django 3.1.5 on 2021-03-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0012_auto_20210314_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watch_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='finish_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='start_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
