# Generated by Django 3.1.5 on 2021-04-02 18:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0013_auto_20210318_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('imdb_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='watchlist.watchlist')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('seen', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='watchlist.actor')),
                ('movie', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='watchlist.movie')),
                ('show', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='watchlist.show')),
            ],
        ),
    ]
