# Generated by Django 3.1.5 on 2021-04-06 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0015_auto_20210402_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='synopsis',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='movie',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='watchlist.movie'),
        ),
        migrations.AlterField(
            model_name='role',
            name='show',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='watchlist.show'),
        ),
        migrations.AlterField(
            model_name='show',
            name='synopsis',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
